BUTTONS_ROW = {"textAlign": "center", "margin-top": "30px"}
CARD_FOOTER = {"textAlign": "right"}
CHECKBOX_INPUT = {"margin-right": "10px"}
COLUMN_TITLE = {"textAlign": "center"}
EMPTY_ELEMENT = {"display": "none"}
FILE_BROWSER = {"height": 500, "overflow": "scroll"}
GRAPH = {}
INFO_CARD = {"margin-left": 10}
LOAD_RESULTS = {"textAlign": "center"}
SUMMARY_ELEMENT = {"textAlign": "center"}
SECTION_TITLE = {"margin-top": "50px"}
